"""add subscribers

Revision ID: 4494f556e60f
Revises: f80308c1c1e8
Create Date: 2021-05-02 18:47:54.691097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4494f556e60f'
down_revision = 'f80308c1c1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
